### ISSUE TITLE
[seybold] Models@run-time with EMF and CDO

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#6]
Submitted by @cha87de to https://github.com/grammarware/sle16/tree/master/seybold

**Comment by dstrueber** [comment]
I'm stuck getting both the server and the client to run. 
- For the server, a Linux binary is provided, but I have a Windows machine. I tried two things to make the server still work:
  - First, I tried to piece together my own server by downloading the corresponding Windows version of the Eclipse CDO Server distribution. To get the custom projects and configuration files by the authors, I integrated the Windows and Linux server directories via file copy+paste. This did not work: I received  NoClassDefFoundErrors in the CDO plugins during server start-up  (presumably API version mismatches). 
  - Second, I tried to install a Linux VM via VirtualBox. This didn't work as I experienced system crashes during VM startup. Obviously not the authors' fault, but I'm hesitant to continue efforts in this direction.
- For the client component, I installed the required model bundle via-update site and imported the three bundles to my local workspace. But when launching either bundle (using Run As -> OSGi framework), I get the following error. I also googled the error, but none of the  answers I found seemed to address my situation.

`
!ENTRY org.eclipse.equinox.preferences 4 2 2016-09-10 00:48:30.278
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".
!STACK 0
java.lang.IllegalStateException: Workbench has not been created yet.
    at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
    at org.eclipse.debug.internal.ui.DebugUIPreferenceInitializer.setThemeBasedPreferences(DebugUIPreferenceInitializer.java:208)
    at org.eclipse.debug.internal.ui.DebugUIPreferenceInitializer.initializeDefaultPreferences(DebugUIPreferenceInitializer.java:81)
    at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:303)
    at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:131)
    at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:368)
    at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:221)
    at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:274)
    at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:409)
    at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:670)
    at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:812)
    at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
    at org.eclipse.core.runtime.preferences.DefaultScope.getNode(DefaultScope.java:76)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getDefaultPreferences(ScopedPreferenceStore.java:238)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getPreferenceNodes(ScopedPreferenceStore.java:269)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.internalGet(ScopedPreferenceStore.java:419)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getString(ScopedPreferenceStore.java:463)
    at org.eclipse.debug.internal.ui.launchConfigurations.PerspectiveManager.initPerspectives(PerspectiveManager.java:994)
    at org.eclipse.debug.internal.ui.launchConfigurations.PerspectiveManager.startup(PerspectiveManager.java:287)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.start(DebugUIPlugin.java:552)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
    at org.eclipse.osgi.container.Module.doStart(Module.java:571)
    at org.eclipse.osgi.container.Module.start(Module.java:439)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
`

**Comment by jlcanovas** [comment]
The artefact is part of the submission "Experiences of models@run-time with EMF and CDO" and includes the implementation to perform the performance experiences reported in the paper.

The artefact has been deployed and tested in a Win10 machine with i7 and 8 gb of RAM. 

As the artefact does not include indications to be deployed in a Windows machine, I used Virtual Box 5.1. However, no virtual machine image was provided, so I had to walk the long road to configure everything. I describe below the steps I followed.

**Virtual Machine**
1. Download Ubuntu 14.04 virtual box image.

**Server**
1. Install openjdk-7-jdk 
2. Install mysql 
3. Import SQL tables. The database dump does not include `CREATE SCHEMA` so a name had to be given. I wonder how the CDO server should be configured to be able to access to the data.
4. Execute the CDO server. I received this error:

```
[INFO] CDO server starting
[WARN] CDO server configuration not found: /home/osboxes/cdoserver/cactos-cdo-server-mysql-final/config/cdo-server.xml
[INFO] CDO server started
```

**Client**
1. Download Eclipse Mars from https://www.eclipse.org/downloads/packages/eclipse-modeling-tools/mars2
2. Install add-ons from https://sdqweb.ipd.kit.edu/eclipse/cactos/optimisationplan/nightly/
3. Import projects located in `client-bundles`
4. After the import process, the project `CDOBenchmarkClient` raises an error related to the Java version. It requires Java 8. As the GitHub project website indicates that Java 7 is assumed, I changed the Java Build Properties of the project to use Java 7 and the problem was fixed. All the imported projects were correctly compiled.

At this point I assume I have the artefact deployed and I can evaluate the submission.

The documentation is scarce and it is not clear what I should do to execute the artefact. It is said that _an equinox osgi environment is required_ so I assume that the three projects imported are in charge of such. I execute the project named `CDOBenchmarkClient` as OSGi framework but the following error is raised:

```
!ENTRY org.eclipse.equinox.preferences 4 2 2016-09-11 09:52:00.996
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".
!STACK 0
java.lang.IllegalStateException: Workbench has not been created yet.
    at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
    at org.eclipse.debug.internal.ui.DebugUIPreferenceInitializer.setThemeBasedPreferences(DebugUIPreferenceInitializer.java:208)
    at org.eclipse.debug.internal.ui.DebugUIPreferenceInitializer.initializeDefaultPreferences(DebugUIPreferenceInitializer.java:81)
    at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:303)
    at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:131)
    at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:368)
    at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:221)
    at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:274)
    at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:409)
    at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:670)
    at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:812)
    at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
    at org.eclipse.core.runtime.preferences.DefaultScope.getNode(DefaultScope.java:76)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getDefaultPreferences(ScopedPreferenceStore.java:238)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getPreferenceNodes(ScopedPreferenceStore.java:269)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.internalGet(ScopedPreferenceStore.java:419)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getString(ScopedPreferenceStore.java:463)
    at org.eclipse.debug.internal.ui.launchConfigurations.PerspectiveManager.initPerspectives(PerspectiveManager.java:994)
    at org.eclipse.debug.internal.ui.launchConfigurations.PerspectiveManager.startup(PerspectiveManager.java:287)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.start(DebugUIPlugin.java:552)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
    at org.eclipse.osgi.container.Module.doStart(Module.java:571)
    at org.eclipse.osgi.container.Module.start(Module.java:439)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

I see that @dstrueber also found the same error. After some research, I did not find any quick fix to this either.

**Comment by tdegueul** [comment]
I encounter the same error as @dstrueber and @jlcanovas. The `Workbench has not been created yet` error made me think that maybe the projects should be launched as an Eclipse application, in which case I get this other error:

```
!SESSION 2016-09-11 22:08:06.123 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /home/dig/workspace/aec/2/../runtime-EclipseApplication -dev file:/home/dig/workspace/aec/2/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.eclipse.equinox.ds 2 0 2016-09-11 22:08:36.918
!MESSAGE [SCR] Enabling components of bundle eu.cactosfp7.cdosessionclient did not complete in 30000 ms 

!ENTRY org.eclipse.equinox.ds 2 0 2016-09-11 22:08:36.919
!MESSAGE [SCR - WorkThread] Timeout occurred! Thread was blocked on processing [QueuedJob] WorkPerformer: org.eclipse.equinox.internal.ds.SCRManager@78889fcf; actionType 1

!ENTRY org.eclipse.emf.ecore 2 0 2016-09-11 22:08:37.000
!MESSAGE Both 'eu.cactosfp7.identifier' and 'eu.cactosfp7.identifier' register a package for 'http://www.cactosfp7.eu/Identifier/1.0'

!ENTRY org.eclipse.emf.ecore 2 0 2016-09-11 22:08:37.002
!MESSAGE Both 'eu.cactosfp7.infrastructuremodels' and 'eu.cactosfp7.infrastructuremodels' register a package for 'http://www.cactosfp7.eu/PhysicalDCModel/ArchitectureType/1.0'

!ENTRY org.eclipse.emf.ecore 2 0 2016-09-11 22:08:37.003
!MESSAGE Both 'eu.cactosfp7.infrastructuremodels' and 'eu.cactosfp7.infrastructuremodels' register a package for 'http://www.cactosfp7.eu/LogicalDCModel/Hypervisor/1.0'

!ENTRY org.eclipse.emf.ecore 2 0 2016-09-11 22:08:37.004
!MESSAGE Both 'eu.cactosfp7.infrastructuremodels' and 'eu.cactosfp7.infrastructuremodels' register a package for 'http://www.cactosfp7.eu/LogicalDCModel/Core/1.0'

!ENTRY org.eclipse.emf.ecore 2 0 2016-09-11 22:08:37.020
!MESSAGE Both 'eu.cactosfp7.infrastructuremodels' and 'eu.cactosfp7.infrastructuremodels' register an extension parser for 'core'
```

In any case, I think the provided documentation is poor and does not help to reproduce the experiment. I am still curious about reproducing the results, so I will wait on this thread to see if the authors come with a solution.

**Comment by dstrueber** [comment]
Review:

As pointed out earlier in this thread, I was not able to reproduce the experiments based on the given instructions. At the current level of documentation, I see no viable way to determine if the artifact is complete, consistent and easy to reuse.

**Comment by cha87de** [comment]
Dear reviewers,
the cdo server is meant to run on a Linux machine. Since we target a productive environment in a Cloud data centre, this decision is not easily changeable.
Since all three reviewers had issues starting the bundles in equinox, i can come up with an eclipse shared launcher. Would that be helpful?

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact does not conforms to the expectations and is **not** approved for inclusion as auxiliary material for the publication. We are sorry to inform you of this, @cha87de, but all three reviewers had trouble getting it to run, and they also reported on the general lack of documentation that could have helped to walk them through the difficulties.

We do appreciate the complexity of the setup and the hardships of having a CDO server running within a specific environment. Having technical limitations is not the main problem, the problem is the inadequate treatment of them, in form of both documentation in general and clarity in particular.
